services:
  app:
    build: .
    container_name: arise-assignment-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_ENV: development
      APP_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: arise_assignment
      DB_SSLMODE: disable
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16-alpine
    container_name: arise-assignment-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: arise_assignment
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d arise_assignment"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
